pacificclimate/climate-explorer-backend

ce/api/metadata.py
ce/api/stats.py
ce/api/util.py
ce/tests/test_api.py
ce/tests/test_util.py

Fairly self-explanatory... I have added a 'time' key value pair to the dictionary responses of both the `stats()` call and the `metadata()` call.
The `metadata()` call returns a dict of all available times keyed by their integer index while the `stats()` call returns the actual time value for the time index that the user requested (or the mean of all time values if the user omitted the time index).
The only hangup that I can see with returning a mean time is that the time values aren't necessarily consistent within a file if the file represents monthly, seasonal, *and* annual data. This maybe speaks more to a hazard in the `stats()` specs than anything to do with this PR, though.
In any case, I think it's good to go, but please feel free to review.

Include time values in reponses for `stats` and `metadata` API calls

---

ce/api/util.py

Old boolean check would return data for all time steps when requesting January resulting in something very close to the annual value.
As long as this doesn't break anything, the fix is very simple.

Allow 0 as a valid time parameter

---

ce/api/multimeta.py
ce/tests/test_api.py

Fixes #9 
This change fixes the root of the performance problem for `multimeta` by making a single database query and constructing the response from the resulting rows (instead of making a subsequent query for each file to get the variables).
The one problem with this fix is that it eliminates the "time" key from the metadata dictionaries in the `multimeta` response. We talked about doing this "eventually", but this should not be merged until the front-end has been adapted to work w/o time values up front.
Here are the performance differences running on an sqlite3 database with ~7000 files.
```bash
#On master branch
hiebert@cheetah:~$ time curl -s localhost:8000/api/multimeta > /dev/null
real	8m13.092s
user	0m0.008s
sys	0m0.010s
hiebert@cheetah:~$ time curl -s localhost:8000/api/multimeta …
```

Rewrote mulitmeta API call to only make one DB query.

---

ce/api/data.py
ce/api/metadata.py
ce/tests/conftest.py
ce/tests/test_api.py

As mentioned in #15 , the `data` API call should filter out ensembles that are not a part of the application configuration. Additionally, it's possible for datasets to be presented in different time resolutions. For example, one might want to present downscaled climate model output as climatologies (e.g. 17 time steps or time_resolution='other') or as an annual timeseries (e.g. 150 or so timesteps). To do this, one must be able to specify the time_resolution when requesting data.
This PR adds both of those parameters to the `data` request and uses them to filter the available datasets from the model metadata database.

Adds "ensemble_name" and "timescale" as data request params

---

ce/__init__.py
ce/api/multimeta.py
ce/tests/test_api.py
requirements.txt

Flask.cache.memoize does not appear to using optional function argument as part of the cache key. Results in returning old data for a new request containing different arguments. Since #17, this isn't really an issue any more and we should cache at higher level.

Remove flask.cache.memoize from multimeta call

---

ce/api/geo.py

Memoizing the grid mask in `geo.py` depends on having a hashable key and
the choice of that key affects performance. The 'model_id' netcdf
attribute is a decent choice for a key component, however we shouldn't
necessarily assume that it exists in the file. If a file does *not* have
the model_id attribute, this patch assures an automatic cache miss,
which prevents the code from failing altogether.
We still should follow through with issue #11 at some point (which will
obsolete this patch).

Adds an attribute check for automatic cache miss

---

ce/api/multimeta.py
ce/tests/test_api.py

Performance implications are minimal; just one extra attribute per unique_id returned.

Adds 'timescale' attribute to the multimeta call

---

README.md
dp/process-climo-means.sh
dp/requirements.txt

`generate_climos` will typically be used stand-alone on a compute node. It's nice to have installation instructions; installing `climate-explorer-backend` is not a useful option here.
This update also contains an example bash script (actually used) for the standard process of: copy input to temp, run script, copy output to permanent storage.

Add instructions for installing and using generate_climos

---

dp/update_metadata.py

This utility script reads changes to be made from a specified YAML file and applies them to the specified NetCDF file. Updates possible are:
- set global attribute
- delete global attribute
- rename global attribute
Unfortunately, the initial cut at this utility was merged into master some while ago. This PR just fixes a bug and improves the code a little.

Add update-metadata utility

---

dp/tests/test_create_climo_files.py

Noticed an error after I merged master to another branch. Not sure how I missed this, since it tests exactly the code modified to fix #34 :(.
It doesn't help that Travis only runs the main backend tests, and not those for extras (this stuff). But the note in `.travis.yml` explains the problem, and it has no easy fix. Bah.

Fix test for annual climo bound end date

---

ce/api/__init__.py
ce/tests/test_api.py

API requests that are missing required query parameters error out
with an HTTP 400 error. The message has been entirely unhelpful:
"Missing query parameters". This commit adds the names of the
missing query parameters to the error message so the user has some path
forward.

Adds a more descriptive 400 error message

---

ce/__init__.py
ce/api/geo.py
ce/api/util.py
ce/tests/test_geo.py
ce/tests/test_util.py

Fixes #53, fixes #39.
A core operation in the ``climate-explorer-backend`` is take a subset of a climate raster and clip it by a polygon, computing statistics for a specific region. We delegate these spatial operations to the ``rasterio`` library (which in turn uses GDAL for the file I/O).
Previously, we used ``rasterio``'s `rasterize()` method, which "burns" a polygon into a raster. We would then take the mask raster from that operation and union it with the climate raster's existing land/sea mask.
This raised problems, however. The climate raster was an object directly from GDAL and was appropriately projected. whereas the mask output from ``rasterize()`` was essentially just a raw array. It was possible for one array to be flipped vertically, (for example of the array indices started …

Replace rasterio's rasterize() with mask()

---

ce/tests/test_geo.py
requirements.txt
setup.py

Shapely's update from version 1.5 to version 1.6 on August 20th included consolidating all the package's errors in one file. One of the tests in `test_geo.py` references `shapely.ReadingError` and needs to be updated with the new error location.

Update location of ReadingError

---

ce/api/stats.py
ce/api/util.py
ce/tests/test_api.py

The issues in #65 (stats and timeseries API results not varying over the course of the year) seem to have been caused by `util.get_array()` returning data for all time indexes at once in a 3D array [time:lat:lon] when passed an area. Then `numpy.mean()` would calculate the average of the _entire_ array - all four or twelve time indexes, resulting in a "timeseries" of twelve/4 identical values, each of which was the mean of the entire year instead of a single month / season. When no area was passed, a 2D array [lat:lon] would be returned.
I remain uncertain, however, because this seems to have been working at some point in the past - at least in one specific docker container whose functionality I cannot duplicate (even by downloading and running the same image from docker hub) - and …

Slice area-masked array by time index

---

ce/api/multistats.py
ce/api/util.py
ce/tests/test_api.py

Addresses #61.
Travis tests are failing due to the recent update of [Shapely](https://pypi.python.org/pypi/Shapely) from version 1.5 to 1.6. The update changed the location of `ReadingError`, which is used in [test_geo.py](https://github.com/pacificclimate/climate-explorer-backend/blob/master/ce/tests/test_geo.py). PR https://github.com/pacificclimate/climate-explorer-backend/pull/68 fixes that issues and should be merged first.

Enable filtering of stats by time resolution - Resolves #61

---

ce/tests/test_api.py

I have a small change that I'd like to make to the test code, assuming folks (@rod-glover and @corviday) think this is OK.
I've added a short function to abbreviate lengthy unique ids in the test ids, to only include differences that are relevant to the testing. Basically it will make the test output like this:
```
ce/tests/test_api.py::test_stats[metro_van_10-tasmax_mClim_BNU-ESM_historical_r1i1p1_19650101-19701230-tasmax] PASSED
ce/tests/test_api.py::test_stats[metro_van_10-tasmax_sClim_BNU-ESM_historical_r1i1p1_19650101-19701230-tasmax] PASSED
ce/tests/test_api.py::test_stats[metro_van_10-tasmax_aClim_BNU-ESM_historical_r1i1p1_19650101-19701230-tasmax] PASSED
ce/tests/test_api.py::test_stats[metro_van_10-tasmin_mClim_BNU-ESM_historical_r1i1p1_19650101-19701230-tasmin] PASSED …
```

Shorten lengthy unique ids in test ids

---

.travis.yml
ce/tests/conftest.py
ce/tests/test_db.py
requirements.txt
setup.py

All of the tests pass (*really* quickly) on my desktop. Is there any reason *not* to do this? I don't seem much in [CHANGES.txt](https://github.com/mapbox/rasterio/blob/master/CHANGES.txt) that should affect us, but there are a few mentions of `rasterize()`, so maybe it has seen some underlying work.

Upgrade rasterio to new release candidate (from alpha)

---

ce/api/data.py

The` /data` API endpoint is called by the code that generates the Long Term Average graph if the user has selected a multi year mean dataset; it yields a series of values, one for each available period, illustrating change over time. 
This query also adds non-mym datasets to the series, which is not correct, but wasn't an issue and didn't come up until we started using an ensemble with both nominal-time and MYM data.

Use only multi year means for /data query

---

streamflow-api.yaml

Resolves #86 
Updated from initial draft circulated a few weeks ago. Updates:
- Base for streamflow-related endpoints: `services.pacificclimate.org/streamflow/` (not routed_streamflows).
- All resource names plural (e.g., `/streamflow/orders`, not `/streamflow/order`).
- All response bodies are fully fleshed out (or should be).
- Consistent use of hyperlinks in all response bodies.
- Hyperlink `ref` properties are abbreviated (e.g., 'cancel') instead of long-form hyperlink.
- Full factoring of commonalities in schemas, parameters, responses, etc.
Notes: 
- The [Streamflow Architecture document](https://pcic.uvic.ca/confluence/display/CSG/Streamflow+Architecture+II) is a key resource to understanding the lifecycles of Orders and Results. 
- See also [Streamflow API Design …

Add streamflow API spec

---

ce/api/data.py
ce/api/lister.py
ce/api/models.py
ce/api/multimeta.py
ce/api/multistats.py
ce/api/stats.py
ce/tests/conftest.py
ce/tests/test_api.py

Resolves #94 
The docs were slightly out of date for the ```time``` and ```timescale``` args in ```multistats.py``` and ```stats.py```.  Furthermore, the default ensemble name has been updated to ```ce_files```.  Other than those small things the docs looks great!

Fix API Documentation

---

ce/api/util.py
ce/tests/test_api.py

The `cell_methods` filter I implemented in PR #96 did not function as I intended.  It would grab `standard_deviation` data file ids while filtering for `mean` data file ids which was not a desirable behaviour.  The solution was to add some more structure to the logic of the filter.  Any climatological standard deviations will have an expected `cell_method` that we can regex for rather simply.  However the climatological means do not consistently use `cell_method` correctly.  To fix this I added a pattern to match for the correct `cell_method` and ignore other cases.  These ignored cases would be checked against the filter for `standard_deviation` and if they did not match they would be considered means.  This resolves issue #98.

Fix cell_methods filter

---

setup.py

According to the [netCDF4 changelog for version 1.4.0](https://github.com/Unidata/netcdf4-python/blob/86f7f4f857422f885dddb087aa985fe9a6096686/Changelog#L99):
```
* always return masked array by default, even if there are no
masked values (too surprising to get ndarray or MaskedArray depending
on slice, issue #785).
```
Previous to version 1.4 of netCDF4, data would be returned as a masked array only if some of it was missing / masked. The backend's processing of latitude and longitude assume that these variables are _not_ masked arrays, so the backend does not work correctly with versions of netCDF4 >= 1.4. For example, [make_mask_grid_key()](https://github.com/pacificclimate/climate-explorer-backend/blob/master/ce/api/geo.py#L137)  expects longitude[0] to be type np.float, which is true …

Pin netCDF4 at <1.4 in setup.py

---

.travis.yml

Drop support for Python <3.6

---

ce/api/multimeta.py
requirements.txt

After upgrading SQLAlchemy to version 1.3.17, the tests that use `multimeta.py` failed due to `Can't determine which FROM clause to join from, there are multiple FROMS which can join to this entity` errors. These were fixed by specifying on which attributes the tables should join wherever there was an ambiguity.

Update SQLAlchemy to version 1.3.17 and fix multimeta tests

---

.github/workflows/ci-tests.yml
.github/workflows/docker-publish.yml
.github/workflows/image-scan.yml

Adds github actions to the repo.  The workflows will take over the responsibilities of Jenkins and Travis which are:
- run python test suite (on all pushes)
- build and publish docker image (on all branches + on tag creation)
- anchore scan docker image (on PRs targeting `master`)
I do not have permission to access the webhooks in this repo but Travis and Jenkins need to be deactivated.

Add Github Actions

---

.github/workflows/ci-tests.yml
ce/api/geo.py
ce/api/util.py
ce/tests/conftest.py
ce/tests/test_geo.py
docker/Dockerfile.prod
requirements.txt
setup.py

The `python-netCDF4` library has released a couple of minor versions, and I think it's time to circle back on the decision that we made in #97 
This PR:
+ adds a test for our `geo` module that ensures that the array results that come back from a netCDF file are in fact scalars and hashable (which I believe was the original problem for the P2A rules engine)
+ upgrades `netCDF4` to 1.5 to demostrate the tests (expectedly) *failing*, and then
+ implements the fix
You can see the results form each step [in the Actions output](https://github.com/pacificclimate/climate-explorer-backend/actions?query=branch%3Aupgrade-netCDF4).
I'm pretty sure that it works well, but I'm happy to have another couple pair of eyes on this, just in case.

Upgrade python-netCDF4 requirement to 1.5

---

ce/api/metadata.py
ce/api/multimeta.py
ce/tests/api/test_api_misc.py
ce/tests/api/test_metadata.py
ce/tests/api/test_multimeta.py
ce/tests/conftest.py
ce/tests/helpers/test_utils.py
doc/source/api/metadata-api-usage.md
doc/source/api/multimeta-api-usage.md
doc/source/workflow.md

Resolves #149 
This PR adds an `extras` param to ` /metadata` and `/multimeta`, which can take a comma-separated list of extra properties to provide for each file it returns. Currently, the single valid value is  `filepath`, which adds a `filepath` property containing ... wait for it ... the file's filepath.
There are also some improvements in tests, and some blackening of code. The bulk of changes is data for tests.

Provide filepath in /metadata and /multimeta responses

---

.pre-commit-config.yaml
README.md
test_requirements.txt

Resolves #158.
- Add `pre-commit` configuration file
- Update `README`
`pre-commit` was a great idea @rod-glover! I'm really happy with the interaction on the terminal. It will be nice to prevent simple styling from breaking actions (although it is good we are still checking for it there). The `pip` package is not in either of the requirements files because it was breaking github actions.

Add pre-commit hook

---

doc/source/api/api-overview.md
doc/source/conf.py
doc/source/workflow.md
requirements.txt

This pull request resolves #130 
It looks like m2r is no longer maintained but I found [m2r2](https://pypi.org/project/m2r2/) which is forked off the original m2r repository and it seems to work with sphinx version > 3 although I'm not 100% confident on what the expected output is when you run `python setup.py build_sphinx`...

Use m2r2 instead of m2r

---

ce/api/data.py
ce/api/util.py
ce/tests/conftest.py

This pull request should resolve #106 
- Adds filter by ensemble name to `get_units_from_run_variable` in `util.py`
- Adds test instance in conftest.py by adding 2 datafilevariables with the same variable name but different units and ensembles

Add ensemble name filter to get_units_from_file_object

---

.github/workflows/python-ci.yml
Makefile
ce/api/data.py
ce/api/geo.py
ce/api/multistats.py
ce/api/stats.py
ce/api/util.py
ce/tests/api/test_data.py
ce/tests/api/test_stats.py
ce/tests/conftest.py
ce/tests/test_geo.py
ce/tests/test_util.py
pytest.ini

This allows `multistats/stats` to optionally target data from the `thredds` server. There is a bit of undesired manipulation that has to happen (namely copying the data to a `tempfile`) due to `rasterio`'s limitations.
Resolves #170.

Thredds data

---

ce/api/data.py
ce/api/multistats.py
ce/api/util.py
ce/tests/api/test_data.py
ce/tests/api/test_multistats.py
ce/tests/conftest.py
ce/tests/test_util.py
requirements.txt

This PR enhances the back end's ability to filter datasets based on a "cell_method" parameter passed to the API by a user, to support some new datasets (model ensemble percentiles) from Hydrology. These parameters are used to request data from only a specific type of statistical dataset, either:
* climatological mean / model ensemble mean (param:  `mean` - the default, used by all current PCEX functionality)
* climatological standard deviation (param: `standard_deviation` - used by plan2adapt's rules engine)
* model ensemble percentile (param: `percentile` - will be used by new portal for the hydrology data)
The following changes were made:
1. switch from parsing cell methods strings with regexes to parsing them with the [cf-cell-methods …

Update "cell methods" parsing to support new Hydrology data

---

ce/api/data.py
ce/api/util.py
ce/tests/test_util.py
requirements.txt

This PR speeds up the `/data` query by  streamlining `get_units_from_run_object()`.
`get_units_from_run_object()` checks all datasets associated with a particular run and variable to make sure they all have the same units and can be aggregated. Previously, the units were checked incrementally by getting the units from each datafile and comparing them. The rewritten function instead gets a list of all units at once from the database.
Timing information:
| Branch      | time to complete sample /data call |
|-------------|------------------------------------|
| [3.1.0](http://docker-dev01.pcic.uvic.ca:30399/api/data?ensemble_name=ce_files&model=CNRM-CM5&variable=fdd&emission=historical,rcp85&timescale=yearly&time=0&area=)       | 1.372 seconds                      |
| …

Speed up /data API

---

ce/api/multimeta.py
ce/tests/api/test_api_misc.py
ce/tests/api/test_multimeta.py
ce/tests/api/test_regions.py

This is a companion PR to #176, which added the ability to specify a cell_methods parameter (either "mean", "percentile", or "standard_deviation") to the `/data` API in order to support displaying datasets that are percentiles of a model ensemble. (The `/multistats` API already had this capability.)
This PR adds the same capacity to the `/multimeta` API.

Add filtering on cell_methods to multimeta API

---

ce/api/data.py
ce/api/multimeta.py
ce/api/multistats.py
ce/api/util.py
ce/tests/api/test_api_misc.py
ce/tests/api/test_data.py
ce/tests/api/test_multimeta.py
ce/tests/api/test_multistats.py
ce/tests/test_util.py

The PR adds a a `climatological_statistic` attribute to the `multimeta` API for climatology datasets. This allows the front end to have access to metadata on whether a dataset is a climatological mean, climatological standard deviation, or climatological percentile, which the front end will use to decide how to display each dataset, and which datasets to request more informaion on. The backend determines which sort of climatology a dataset is by parsing the `cell_methods` attribute of the dataset. If the `cell_methods` attribute is unparsable, the dataset is assumed to be a climatological mean.
In addition, some extra changes were made for clarity. There is now a clear distinction in the code between `cell_methods`, which refers to the `cell_methods` attribute of a dataset, describing the …

Add climatological_statistic attribute to multimeta

---

ce/api/data.py
ce/api/multimeta.py
ce/api/multistats.py
ce/api/stats.py
ce/api/streamflow/watershed.py
ce/api/util.py
ce/tests/test_util.py

This PR extends the `climatological_statistic` parameter, with which a user specifies whether they want data from climatological means, climatological standard deviations, or climatological percentiles.The new parameter is called `percentile` and allows a user to specify exactly _which_ percentile values they would like data or metadata from, 5th percentile, 50th percentile, etc. 
The new `percentile` parameter has been added to all the APIs where one selects multiple datasets by specifying a set of parameters that describe them: `multimeta`, `multistats`, and `data`. For `multistats` and `data`, the `percentile` parameter must be specified if the `climatological_statistics` is `percentile`. That is,  with these two APIs, you cannot merely filter to all percentile datasets, you must …

Allow filtering by Nth percentile in data,multimeta, and multistat

---

ce/api/streamflow/watershed.py
ce/geo_data_grid_2d/vic/__init__.py
ce/tests/api/streamflow/watershed/conftest.py
ce/tests/api/streamflow/watershed/test_watershed.py

**Motivation**
While testing the new Melton ratio code, @AreliaTW discovered that the results were consistently lower than expected in the Upper Fraser. 
She traced the issue to our elevation dataset. The elevation dataset we are using records the mean elevation of each grid cell. The mean elevation dataset has the same grid as the flow direction dataset, which facilitates this endpoint's calculations. First it determined the extent of a watershed using the flow direction dataset, then it can project that extent directly onto other datasets (elevation, area) with the same grid to do further calculations.
Unfortunately, this grid is too coarse to record the highs and lows in terrain needed to calculate the Melton ratio, which is determined by dividing the difference between the highest and …

Use min and max elevation datasets to calculate the Melton ratio in watershed

---

.github/workflows/python-ci.yml
Pipfile
Pipfile.lock
ce/geo_data_grid_2d/__init__.py
docker/Dockerfile.prod

This PR speeds up the APIs that interact with the VIC data by modifying GeoDataGrid2D, used to represent time-invariant datasets that describe the physical landscape underlaying data (elevation minimum, elevation maximum, elevation mean, flow direction, and area) . GeoDataGrid2D preloads latitude, longitude, and variable data by storing it as a numpy array instead of a netCDF variable.
Resolves pacificclimate/climate-explorer-backend#211 
This branch needs more testing before it can be merged.

Speed up watershed-related APIs

---

doc/source/api/api-index.rst
doc/source/api/downstream-api-usage.md
doc/source/api/downstream-api.rst
doc/source/api/watershed-api-usage.md
doc/source/api/watershed-streams-api-usage.md
doc/source/api/watershed-streams-api.rst

Updates documentation around the streamflow APIs:
* adds documentation for the `downstream` and `watershed_streams` APIs (resolve #216)
* adds documention of the Melton ration provided by @AreliaTW  to the `watershed` API (resolves #193)
@AreliaTW also provided images illustrating the Melton Ratio, but I am not sure how to include them. I shortened her text slightly for the purposes of an API document - API users don't need to know how the files are organized on the backend.

Document watershed APIs

---

ce/api/__init__.py
ce/tests/api/test_api_misc.py
ce/views.py
doc/source/api/api-overview.md

Updates the backend to accept HTTP `POST` requests in addition to HTTP `GET`. This is a straightforward update thanks to Flask's handy `request.values` attribute, which contains all parameters supplied either in the URL of a `POST` or the body of a `GET`, allowing the request methods to be treated identically.
The goal here is to be able to accept longer `area` strings, especially from user-selected regions, such as when a user clicks on a point in a flow network to select all grid squares upstream of that point. One notable example of selecting an upstream area along the FRASER river results in an `area` string ten thousand characters long, too long to send in a URL.
resolves #227

Accept POST requests

---

NEWS.md
pyproject.toml

This release has no code changes written by us, but tests that began spontaneously failing in 3.6.2 are working again, so it is likely some library we use has changed. The release exists for the sole purpose of getting that library change into docker containers.

Bump to 3.6.3

---

.github/workflows/pypi-publish.yml
.github/workflows/python-ci.yml
ce/api/geo.py
docker/Dockerfile.dev
docker/Dockerfile.prod

Switches to [a newer version of the geospatial-python docker](https://github.com/pacificclimate/docker-geospatial-python) to fix a couple issues with the build. The new docker has ubuntu 22.04 (was previously ubuntu 18.04), gdal 3.4 (was previously 2.3.1), and python 3.10 (was previously 3.8).
A couple updates to imports to bring the code into line with python 3.10.
[Demo](https://beehive.pacificclimate.org/scip/app/) of SCIP with this backend.
resolves #233 
resolves #243

Update to python 3.10
